spring:
  datasource:
    url: jdbc:sqlite:voucher.db
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    security: DEBUG
    web: DEBUG
    org:
      springframework:
        security: DEBUG
        data: INFO
